# Uffizzi extension (required)
x-uffizzi:
  ingress:
    service: loadbalancer
    port: 8080  
  continuous_previews:
    delete_preview_after: 2h

# Vote application
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 500M

  worker:
    image: uffizzitest/worker:latest
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    image: uffizzitest/result:latest
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PORT: 8088

  vote:
    image: uffizzitest/vote:latest
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      PORT: 8888

  loadbalancer:
    image: uffizzitest/loadbalancer:latest
    environment:
      PORT: 8080
      VOTE_HOST: "localhost"
      VOTE_PORT: "8888"
      RESULT_HOST: "localhost"
      RESULT_PORT: "8088"
    deploy:
      resources:
        limits:
          memory: 125M
